// Code generated by Kitex v0.9.1. DO NOT EDIT.

package captchaservice

import (
	captcha "captcha/kitex_gen/captcha"
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	EmailCaptcha(ctx context.Context, Req *captcha.EmailCaptchaRequest, callOptions ...callopt.Option) (r *captcha.EmailCaptchaResponse, err error)
	EmailValidate(ctx context.Context, Req *captcha.EmailValidateRequest, callOptions ...callopt.Option) (r *captcha.EmailValidateResponse, err error)
	EmailRefresh(ctx context.Context, Req *captcha.EmailRefreshRequest, callOptions ...callopt.Option) (r *captcha.EmailRefreshResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kCaptchaServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kCaptchaServiceClient struct {
	*kClient
}

func (p *kCaptchaServiceClient) EmailCaptcha(ctx context.Context, Req *captcha.EmailCaptchaRequest, callOptions ...callopt.Option) (r *captcha.EmailCaptchaResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.EmailCaptcha(ctx, Req)
}

func (p *kCaptchaServiceClient) EmailValidate(ctx context.Context, Req *captcha.EmailValidateRequest, callOptions ...callopt.Option) (r *captcha.EmailValidateResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.EmailValidate(ctx, Req)
}

func (p *kCaptchaServiceClient) EmailRefresh(ctx context.Context, Req *captcha.EmailRefreshRequest, callOptions ...callopt.Option) (r *captcha.EmailRefreshResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.EmailRefresh(ctx, Req)
}
