// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameFile = "files"

// File mapped from table <files>
type File struct {
	FileID           string         `gorm:"column:file_id;primaryKey;type:char(36)" json:"file_id"`
	FileName         string         `gorm:"column:file_name;not null;type:varchar(255)" json:"file_name"`
	FilePath         string         `gorm:"column:file_path;not null;type:varchar(255)" json:"file_path"`
	FileSize         int64          `gorm:"column:file_size;not null;type:bigint" json:"file_size"`
	OwnerID          string         `gorm:"column:owner_id;not null;type:char(36)" json:"owner_id"`
	AccessLevel      int32          `gorm:"column:access_level;type:tinyint;default:0" json:"access_level"`
	FilePasswordHash string         `gorm:"column:file_password_hash;type:varchar(255);default:null" json:"file_password_hash"`
	CheckSum         string         `gorm:"column:check_sum;not null;type:char(32)" json:"check_sum"`
	CreatedAt        time.Time      `gorm:"column:created_at;type:timestamp(6);default:CURRENT_TIMESTAMP(6)" json:"created_at"`
	UpdatedAt        time.Time      `gorm:"column:updated_at;type:timestamp(6);default:CURRENT_TIMESTAMP(6);autoUpdateTime" json:"updated_at"`
	DeletedAt        gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName File's table name
func (*File) TableName() string {
	return TableNameFile
}
