// Code generated by Kitex v0.9.1. DO NOT EDIT.

package fileservice

import (
	"context"
	file "file/kitex_gen/file"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Upload(ctx context.Context, Req *file.UploadRequest, callOptions ...callopt.Option) (r *file.UploadResponse, err error)
	Download(ctx context.Context, Req *file.DownloadRequest, callOptions ...callopt.Option) (r *file.DownloadResponse, err error)
	Check(ctx context.Context, Req *file.CheckRequest, callOptions ...callopt.Option) (r *file.CheckResponse, err error)
	Delete(ctx context.Context, Req *file.DeleteRequest, callOptions ...callopt.Option) (r *file.DeleteResponse, err error)
	Detail(ctx context.Context, Req *file.DetailRequest, callOptions ...callopt.Option) (r *file.DetailResponse, err error)
	Update(ctx context.Context, Req *file.UpdateRequest, callOptions ...callopt.Option) (r *file.UpdateResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kFileServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kFileServiceClient struct {
	*kClient
}

func (p *kFileServiceClient) Upload(ctx context.Context, Req *file.UploadRequest, callOptions ...callopt.Option) (r *file.UploadResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Upload(ctx, Req)
}

func (p *kFileServiceClient) Download(ctx context.Context, Req *file.DownloadRequest, callOptions ...callopt.Option) (r *file.DownloadResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Download(ctx, Req)
}

func (p *kFileServiceClient) Check(ctx context.Context, Req *file.CheckRequest, callOptions ...callopt.Option) (r *file.CheckResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Check(ctx, Req)
}

func (p *kFileServiceClient) Delete(ctx context.Context, Req *file.DeleteRequest, callOptions ...callopt.Option) (r *file.DeleteResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Delete(ctx, Req)
}

func (p *kFileServiceClient) Detail(ctx context.Context, Req *file.DetailRequest, callOptions ...callopt.Option) (r *file.DetailResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Detail(ctx, Req)
}

func (p *kFileServiceClient) Update(ctx context.Context, Req *file.UpdateRequest, callOptions ...callopt.Option) (r *file.UpdateResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Update(ctx, Req)
}
